<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title></title>
        <script src="../public/js/jquery.min.js"></script>
        <script src="../public/lib/layui/layui.all.js"></script>
        <script src="../public/lib/layer/dist/layer.js"></script>
        <link rel="stylesheet" href="../public/lib/layui/css/layui.css">
    </head>
    <body>
    </body>
</html>
